# Generated by Django 2.2.7 on 2019-11-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('po', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('qty', models.IntegerField()),
            ],
        ),
    ]
