# Generated by Django 2.2.7 on 2019-11-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0002_auto_20191121_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='po',
        ),
    ]
