# Generated by Django 2.2.7 on 2019-11-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0003_auto_20191121_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
